pipeline {
  environment {
    registry = "crobles10/summit_2019"
    registryCredential = 'docker-hub'
    dockerImage = ''
  }
  
  agent any
  stages {
    stage('Cloning repository') {
      steps{
        /* Cloning the Repository to our Workspace */
        checkout scm
      }
    }
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }
  }
}